export const CITIES = {
  "Andhra Pradesh": [
    "Amaravati",
    "Guntur",
    "Nellore",
    "Tirupati",
    "Vijayawada",
    "Visakhapatnam",
  ],
  "Arunachal Pradesh": [
    "Bomdila",
    "Bhismaknagar",
    "Itanagar",
    "Pasighat",
    "Tawang",
    "Ziro",
  ],
  Assam: ["Dibrugarh", "Guwahati", "North Lakhimpur", "Silchar", "Tezpur"],
  Bihar: ["Bhagalpur", "Biharsharif", "Darbhanga", "Gaya", "Patna"],
  Chhattisgarh: [
    "Bilaspur",
    "Durg",
    "Korba",
    "Raigarh",
    "Raipur",
    "Rajnandgaon",
  ],
  Goa: ["Goa Velha", "Mapusa", "Margao", "Panaji", "Ponda", "Vasco-da-Gama"],
  Gujarat: [
    "Ahmedabad",
    "Gandhinagar",
    "Junagadh",
    "Rajkot",
    "Surat",
    "Vadodara",
  ],
  Haryana: ["Ambala", "Faridabad", "Gurgaon", "Panipat", "Sonipat"],
  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Dharamshala",
    "Mandi",
    "Shimla",
    "Solan",
  ],
  Jharkhand: [
    "Bokaro Steel City",
    "Deoghar",
    "Dhanbad",
    "Hazaribagh",
    "Jamshedpur",
    "Ranchi",
  ],
  Karnataka: [
    "Belgaum",
    "Bengaluru",
    "Davangere",
    "Hubli-Dharwad",
    "Mangalore",
    "Mysore",
  ],
  Kerala: [
    "Kochi",
    "Kozhikode",
    "Malappuram",
    "Thiruvananthapuram",
    "Thrissur",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Gwalior",
    "Indore",
    "Jabalpur",
    "Sagar",
    "Ujjain",
  ],
  Maharashtra: ["Aurangabad", "Mumbai", "Nagpur", "Nashik", "Pune", "Solapur"],
  Manipur: [
    "Bishnupur",
    "Chandel",
    "Imphal",
    "Senapati",
    "Tamenglong",
    "Ukhrul",
  ],
  Meghalaya: [
    "Baghmara",
    "Cherrapunji",
    "Jowai",
    "Nongpoh",
    "Shillong",
    "Tura",
  ],
  Mizoram: ["Aizawl", "Champhai", "Lunglei", "Mamit", "Serchhip", "Tuipang"],
  Nagaland: [
    "Kiphire Sadar",
    "Kohima",
    "Mokokchung",
    "Phek",
    "Tuensang",
    "Zunheboto",
  ],
  Odisha: [
    "Bhubaneswar",
    "Brahmapur",
    "Cuttack",
    "Puri",
    "Rourkela",
    "Sambalpur",
  ],
  Punjab: [
    "Amritsar",
    "Chandigarh",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Patiala",
  ],
  Rajasthan: ["Ajmer", "Bikaner", "Jaipur", "Jaisalmer", "Jodhpur", "Udaipur"],
  Sikkim: ["Gangtok", "Gyalshing", "Mangan", "Namchi", "Rabdentse"],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Erode",
    "Madurai",
    "Tiruchirappalli",
    "Vellore",
  ],
  Telangana: [
    "Adilabad",
    "Hyderabad",
    "Karimnagar",
    "Khammam",
    "Nizamabad",
    "Warangal",
  ],
  Tripura: [
    "Agartala",
    "Amarpur",
    "Gakulnagar",
    "Kumarghat",
    "Kunjaban",
    "Udaipur",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Allahabad (Prayagraj)",
    "Kanpur",
    "Lucknow",
    "Noida",
    "Varanasi",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Haldwani",
    "Kashipur",
    "Rishikesh",
    "Roorkee",
  ],
  "West Bengal": [
    "Asansol",
    "Darjeeling",
    "Durgapur",
    "Howrah",
    "Kolkata",
    "Siliguri",
  ],
};
